name: ${project.name}
main: com.michaelelin.holoban.HoloBan
version: ${project.version}
description: ${project.description}
website: ${project.url}
authors: [Dumbo52]
api-version: 1.14

commands:
  holoban-reload:
    description: Reloads HoloBan's configuration
    permission: holoban.admin
