name: ${project.name}
main: com.michaelelin.holoban.HoloBan
version: ${project.version}
description: ${project.description}
website: ${project.url}
authors: [Dumbo52]
api-version: 1.14

permissions:
  holoban.notify:
    description: Permission to receive notifications about blocked actions.

  holoban.bypass:
    description: Permission to bypass all restrictions.

  holoban.admin:
    description: Permission to use /holoban-reload.

commands:
  holoban-reload:
    description: Reloads HoloBan's configuration
    permission: holoban.admin
